language: node_js
node_js:
  - "5"
  - "6"
  - "7"

install:
  - cd $TRAVIS_BUILD_DIR && npm install

script:
  - cd $TRAVIS_BUILD_DIR && npm test

cache:
  directories:
    - "qsa-js/node_modules"

sudo: false
